name: Production Workflow - Build and deploy to production

on:
  pull_request:
    types:
    - closed
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up headless firefox and install geckodriver
      run: |
        chmod +x .github/scripts/selenium-setup.sh
        ./.github/scripts/selenium-setup.sh
    
    - name: Decrypt Cloud Storage service account
      run: |
        chmod +x .github/scripts/decrypt.sh
        ./.github/scripts/decrypt.sh
      env:
        SECRET_FILE_PASSPHRASE: ${{secrets.GS_SA_PASSPHRASE}}
        SECRET_FILE: ${{secrets.GS_SA_KEY}}
    
    - name: Run tests and create app.yaml
      run: |
        python manage.py test
        python app.yaml.py
      env:
        # Django
        SECRET_KEY: ${{secrets.SECRET_KEY}}
        ALLOWED_HOSTS: ${{secrets.ALLOWED_HOSTS}}
        DEBUG: ${{secrets.DEBUG}}

        # Email
        EMAIL_HOST_USER: ${{secrets.EMAIL_HOST_USER}}
        EMAIL_HOST_PASSWORD: ${{secrets.EMAIL_HOST_PASSWORD}}
        ADMINS: ${{secrets.ADMINS}}
        MANAGERS: ${{secrets.MANAGERS}}

        # Cloud Storage
        GS_BUCKET_NAME: ${{secrets.GS_BUCKET_NAME}}
        GS_SA_KEY: ${{secrets.GS_SA_KEY}}

        # Cloud SQL
        INSTANCE_CONNECTION_NAME: ${{secrets.INSTANCE_CONNECTION_NAME}}
        DATABASE: ${{secrets.DATABASE}}
        USER: ${{secrets.USER}}
        PASSWORD: ${{secrets.PASSWORD}}
      
    - name: Decrypt App Engine service account
      run: |
        chmod +x .github/scripts/decrypt.sh
        ./.github/scripts/decrypt.sh
      env:
        SECRET_FILE_PASSPHRASE: ${{secrets.GAE_SA_PASSPHRASE}}
        SECRET_FILE: ${{secrets.GAE_SA_KEY}}
      
    - name: Deploy the project to App Engine Standard
      run: |
        chmod +x .github/scripts/deploy-gae.sh
        ./.github/scripts/deploy-gae.sh
      env:
        GAE_SA_KEY: ${{secrets.GAE_SA_KEY }}
        GCP_PROJECT_ID: ${{secrets.GCP_PROJECT_ID}}
